name: Deploy Frontend (PROD)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/deploy-frontend.yml
        with:
          image_name: festiplanner-frontend-prod:${{ github.sha }}
          container_name: festiplanner-frontend-prod
          port: "3000"
        secrets:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}