name: Deploy Frontend (PROD)

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: prod
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      environment: prod
      image_name: festiplanner-frontend-prod:${{ github.sha }}
      container_name: festiplanner-frontend-prod
      port: "3000"
    secrets: inherit