name: Deploy Frontend (DEV)

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_BASE_PATH=${{ vars.VITE_BASE_PATH }} \
            -t festiplanner-frontend-dev:${{ github.sha }} .

      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          docker save festiplanner-frontend-dev:${{ github.sha }} > image.tar

          scp -i ~/.ssh/id_rsa image.tar ${{ secrets.USER }}@${{ secrets.HOST }}:/home/ubuntu/

          ssh -i ~/.ssh/id_rsa ${{ secrets.USER }}@${{ secrets.HOST }} << EOF

            docker load < /home/ubuntu/image.tar

            docker stop festiplanner-frontend-dev || true
            docker rm festiplanner-frontend-dev || true

            docker run -d \
              --name festiplanner-frontend-dev \
              --restart unless-stopped \
              -p 8080:80 \
              festiplanner-frontend-dev:${{ github.sha }}

          EOF