name: Deploy Frontend (DEV)

on:
  push:
    branches: [develop]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      environment: dev
      image_name: festiplanner-frontend-dev:${{ github.sha }}
      container_name: festiplanner-frontend-dev
      port: "8080"
    secrets: inherit