name: Frontend Deploy (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_name:
        required: true
        type: string
      container_name:
        required: true
        type: string
      port:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build \
            --build-arg VITE_BASE_PATH=${{ vars.VITE_BASE_PATH }} \
            -t ${{ inputs.image_name }} .

      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          docker save ${{ inputs.image_name }} > image.tar

          scp -i ~/.ssh/id_rsa image.tar ${{ secrets.USER }}@${{ secrets.HOST }}:/home/ubuntu/

          ssh -i ~/.ssh/id_rsa ${{ secrets.USER }}@${{ secrets.HOST }} << EOF

            docker load < /home/ubuntu/image.tar

            docker stop ${{ inputs.container_name }} || true
            docker rm ${{ inputs.container_name }} || true

            docker run -d \
              --name ${{ inputs.container_name }} \
              --restart unless-stopped \
              -p ${{ inputs.port }}:80 \
              ${{ inputs.image_name }}

          EOF